spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/otboo
    username: otboo
    password: otboo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug